# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

C_order_desc <- function(x) {
    .Call(`_cnaOpt_C_order_desc`, x)
}

C_ccoKeep <- function(con, cov) {
    .Call(`_cnaOpt_C_ccoKeep`, con, cov)
}

C_msubset <- function(x, s) {
    .Call(`_cnaOpt_C_msubset`, x, s)
}

C_getOptim <- function(x) {
    .Call(`_cnaOpt_C_getOptim`, x)
}

C_append <- function(x, y) {
    .Call(`_cnaOpt_C_append`, x, y)
}

C_mappend <- function(x, y) {
    .Call(`_cnaOpt_C_mappend`, x, y)
}

repTrueFalse <- function(len, ntrue) {
    .Call(`_cnaOpt_repTrueFalse`, len, ntrue)
}

C_iterate2 <- function(dx, dminxy, Sx_base, Sy, blksize = 10000L, verbose = TRUE) {
    .Call(`_cnaOpt_C_iterate2`, dx, dminxy, Sx_base, Sy, blksize, verbose)
}

resize <- function(x, n) {
    .Call(`_cnaOpt_resize`, x, n)
}

C_mhs_iteration <- function(m, m_x, m_sol) {
    .Call(`_cnaOpt_C_mhs_iteration`, m, m_x, m_sol)
}

